### ISSUE TITLE
UUID get cut off on Pixel 2 XL with some UUIDs

### ISSUE THREAD

**Issue by cprice70** [Bridouille/android-beacon-scanner#11]
In portrait mode, some UUIDs get wrapped and as a result, the text gets
cut off at the top.  See attached screenshot for an example.

![screenshot_20180204-142521](https://user-images.githubusercontent.com/12190887/35781550-84b60e82-09b9-11e8-9a6a-20fc454562c7.png)

**Comment by Bridouille** [comment]
Thanks for reporting this 👍

**Comment by cheeta1** [comment]
hi @Bridouille  where can i get the licence key to compile this project. kindly point me to that link.
i get this error when try to compile this project. my email is aqib.bookworm@gmail.com

Error:(11, 0) Could not get unknown property 'beacon_scanner_key_password' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=BeaconScannerKey, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
<a href="openFile:C:\Users\CHEETA\AndroidStudioProjects\android-beacon-scanner-master\app\build.gradle">Open File</a>

**Comment by cheeta1** [comment]
hi @Bridouille where can i get the licence key to compile this project. kindly point me to that link.
i get this error when try to compile this project. my email is aqib.bookworm@gmail.com

Error:(11, 0) Could not get unknown property 'beacon_scanner_key_password' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=BeaconScannerKey, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
Open File

**Comment by aj019** [comment]
@cheeta1 I was able to compile it by removing the release config from the build.gradle file

**Comment by Bridouille** [comment]
This is now fixed on master 🤦‍♂
