### ISSUE TITLE
Error while running the project "unknown property "

### ISSUE THREAD

**Issue by wama2** [Bridouille/android-beacon-scanner#12]
Hello, 

I got this error when I import the project:
 "Error:(11, 0) Could not get unknown property 'beacon_scanner_key_password' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=BeaconScannerKey, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
<a href="openFile:D:\charityProject\android-beacon-scanner\app\build.gradle">Open File</a>"

my android Gradle is up to date even I reimport the project twice but I got at the end the same error?

Thanks

**Comment by wama2** [comment]
Thanks a lot 
now it's working

**Comment by joshfernandez** [comment]
Hi, @Bridouille! I was able to add the 3 keys in my `gradle.properties`, but I get `ERROR: No value has been specified for this provider.`

What should I do? Where can I get `/path/to/my/keystore`?
