### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [Bridouille/android-beacon-scanner#14]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, that do not use Google Play nor anything else, except F-Droid.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by Bridouille** [comment]
Hi,

Absolutely, it would be okay for someone else to do that. I have no problem with this app being used adde on F-Droid 👍

**Comment by Poussinou** [comment]
Can this app work without `com.google.firebase:firebase-core`, `com.google.firebase:firebase-crash` and `com.google.gms.google-services` ? Otherwise, we can't include it in F-Droid because these librairies aren't FLOSS.

**Comment by Bridouille** [comment]
Yes it will work, you just need to remove the references from the code. Firebase is only used for analytics.

**Comment by Poussinou** [comment]
Could you write a new build flavor in gradle that removes this libraries at compile time? It would help us, we are busy, and you know your app better than us ;)

**Comment by Bridouille** [comment]
Okay, I don't have time at the moment. But can still leave the issue open for when I have more time.

**Comment by IzzySoft** [comment]
May I ask for a status on this, @Bridouille? In the gradle I still see

    implementation "com.google.firebase:firebase-core:16.0.6"
    implementation "com.google.firebase:firebase-crash:16.2.1"
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.7'

and no separate flavor. Just asking as the RFP mentioned by @Poussinou still waits to be processed – and those libraries keeping it from that.

**Comment by Bridouille** [comment]
I still don't have much time to do it at the moment. I'd need to create a specific flavor without all those dependencies and hide the calls behind an interface I think.

My priority work on this project would be continuing the refactoring I started a month ago first!

**Comment by IzzySoft** [comment]
@Bridouille may I sent a friendly ping before the year is completed? :wink:
