### ISSUE TITLE
Code base

### ISSUE THREAD

**Issue by bantibaghel** [Bridouille/android-beacon-scanner#15]
Hi,

 Have you android-beacon-scanner's code is java based. if yes, please give me a link or source code.
 Because I don't want to use kotlin. 

Thanks
Banti kumar

**Comment by Bridouille** [comment]
Hi,

I'm sorry but the only code base there is, is this one!

**Comment by bantibaghel** [comment]
Thanks for reply, no problem.

But i am facing google-services.json is missing problem.
How can i resole it.

**Comment by Bridouille** [comment]
You need to provide a google-services.json file at the root folder.
Create a project in the Firebase console and put the google-services.json file in your project and it should be ok.
