### ISSUE TITLE
Question : Will this scan continuously if the mobile is kept idle for more than 2 hours. 

### ISSUE THREAD

**Issue by android-bash** [Bridouille/android-beacon-scanner#32]
Question : Will this scan continuously if the mobile is kept idle for more than 2 hours in Android 9.

**Comment by Bridouille** [comment]
Hi, sorry for not answering earlier I completely missed this.
It should work, when scanning the app is holding a wake lock to prevent the device to sleep and therefore stay in the foreground which will allow the app to continuously scan for beacons :)
