### ISSUE TITLE
logging the data

### ISSUE THREAD

**Issue by harsh-agarwal** [Bridouille/android-beacon-scanner#34]
Hi,

I am trying to understand the nature of beacon signals for my research and wanted to log the data for research purpose. 

I created an HTTP logging endpoint using flask and started sending my data! Worked! 

However, when I look at my terminal, it seems that the structure of the data is really messed up.

I am attaching an image of what I received:
![image](https://user-images.githubusercontent.com/11302053/58377674-f58a3780-7f53-11e9-8a28-b985a9404977.png)

Can someone please elaborate on how do I parse it into a proper JSON file? 

Thanks! 

PS: I am new to all this, and it may be trivial, but I have been struggling a lot with it :(

**Comment by harsh-agarwal** [comment]
I fixed it..thanks! :)

**Comment by ap-ubeac** [comment]
> Hi,
> 
> I am trying to understand the nature of beacon signals for my research and wanted to log the data for research purpose.
> 
> I created an HTTP logging endpoint using flask and started sending my data! Worked!
> 
> However, when I look at my terminal, it seems that the structure of the data is really messed up.
> 
> I am attaching an image of what I received:
> ![image](https://user-images.githubusercontent.com/11302053/58377674-f58a3780-7f53-11e9-8a28-b985a9404977.png)
> 
> Can someone please elaborate on how do I parse it into a proper JSON file?
> 
> Thanks!
> 
> PS: I am new to all this, and it may be trivial, but I have been struggling a lot with it :(

Hi, 

I suggest to use this free online HTTP/MQTT hook:
http://hook.ubeac.io/

Thanks!

**Comment by FIVEYOUNGWOO** [comment]
how to extract JSON file from http://hook.ubeac.io/ hook website?

**Comment by pournasserian** [comment]
@FIVEYOUNGWOO hook wouldn't store the data. But, you can create an account on uBeac and create a gateway. Then you will have access to your data through uBeac's API. Also, you can visualize your phone's sensors on the realtime dashboard. Here is the documentation:
https://api.ubeac.io/doc/index.html

**Comment by FIVEYOUNGWOO** [comment]
@pournasserian Thank you for your advice. I solved this problem by using uBeac API :>
