### ISSUE TITLE
Access to the data recorded 

### ISSUE THREAD

**Issue by harsh-agarwal** [Bridouille/android-beacon-scanner#35]
Hi,

The readme suggested that it was using realm for storing and retrieving the data on phone. So I extracted all the realm packages using adb: 

```
#!/bin/bash
ADB_PATH="/Users/harshaga/Library/Android/sdk/platform-tools"
PACKAGE_NAME="com.bridou_n.beaconscanner"
DB_NAME="default.realm"
DESTINATION_PATH="/Users/harshaga/Downloads/${DB_NAME}"
NOT_PRESENT="List of devices attached"
ADB_FOUND=`${ADB_PATH}/adb devices | tail -2 | head -1 | cut -f 1 | sed 's/ *$//g'`
if [[ ${ADB_FOUND} == ${NOT_PRESENT} ]]; then
    echo "Make sure a device is connected"
else
    ${ADB_PATH}/adb exec-out run-as ${PACKAGE_NAME} cat files/${DB_NAME} > ${DESTINATION_PATH}
    echo "Database exported to ${DESTINATION_PATH}"
fi
```

Once done I am trying to use a realm browser, for getting a look at the data. I tried two softwares, Realm Studio and Realm Browser on Mac.

Realm Studio gives me the following error:

Realm file has a bad size (59) Path:.

<img width="900" alt="Screen Shot 2019-06-05 at 6 48 33 PM" src="https://user-images.githubusercontent.com/11302053/58995614-e3659000-87c2-11e9-891d-3f7b1997d29b.png">

For Realm Browser it asks me for an encryption key:

<img width="971" alt="Screen Shot 2019-06-05 at 6 51 56 PM" src="https://user-images.githubusercontent.com/11302053/58995646-042de580-87c3-11e9-9719-38303a532ad9.png">

Any help would be appreciated. I am new to all this, so I might be doing something silly, but I badly need to get this to work :( 

Thank you so much for the app!  

Cheers!
Harsh

**Comment by Bridouille** [comment]
Latest master is not using realm anymore, I refactored it to use Room as the database! I should update the readme, that's my bad.

**Comment by harsh-agarwal** [comment]
Can you please help me by telling me how can I access the data on the phone?

**Comment by Bridouille** [comment]
You can use any tool to browse the SQLite database of the app. In fact you can do it in Android Studio : https://medium.com/@mattyskala/browse-sqlite-database-in-android-studio-4fbba6cca105 - You'd need to build and run the app in development though.

**Comment by harsh-agarwal** [comment]
Ok...Lemme try that and get back to you. Thanks :)
