### ISSUE TITLE
Show which apps respond to beacons?

### ISSUE THREAD

**Issue by akierig** [Bridouille/android-beacon-scanner#36]
Would it be possible to show which apps are listening and responding to beacon calls?

**Comment by Bridouille** [comment]
What do you mean by beacon calls? Beacons are not communicating with your phone, they're just emitting their "signal" and the app recognize them.

**Comment by akierig** [comment]
A better way of putting it might be to ask for which apps on a device are listening for these beacons, though that may be something outside the scope of this project.

**Comment by Bridouille** [comment]
I don't think you can get that information. All apps with Bluetooth permissions can theoretically do that. The only caveat is that when the app is in the background they'd have to use a foreground service to continue scanning, I imagine.

**Comment by akierig** [comment]
Understood. I'll talk to an RF/Bluetooth engineer I know to see if he has any ideas and let you know if we come up with anything. Thanks!
