### ISSUE TITLE
Building project 

### ISSUE THREAD

**Issue by ZahirSoufiane** [Bridouille/android-beacon-scanner#4]
Hi,thks for yr lib :) 
after clonnig your library, i got this issus (building the project build.gradle)
```
Error:Failed to resolve: annotationProcessor
<a href="openFile:C:/Users/Soufian/Desktop/project04/android-beacon-scanner/app/build.gradle">Open File</a>
```
```
Error:(85, 13) Failed to resolve: com.google.firebase:firebase-core:10.2.6
<a href="openFile:C:/Users/Soufian/Desktop/project04/android-beacon-scanner/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```

**Comment by Bridouille** [comment]
Hi,

I've tried to reproduce your issue but it's working fine on my side.
I cloned the repo, added a `google-services.json` file in the `app` folder, and compiled the project without any issue.

Did you manage to solve your issue ?

**Comment by Bridouille** [comment]
No more news here, closing.
