### ISSUE TITLE
Bro!! I am sure you have used some hidden chunks of code to hack user's data.

### ISSUE THREAD

**Issue by akriot** [Bridouille/android-beacon-scanner#44]

**Comment by akriot** [comment]
![Screen Shot 2020-01-17 at 3 55 23 PM](https://user-images.githubusercontent.com/12098036/72605035-04d64f00-3942-11ea-8323-3044700f2495.png)

**Comment by Mechazo11** [comment]
@akriot , which file contains these codes? Can we get rid of them?

**Comment by Jochen1980** [comment]
@akriot @Mechazo11 @Bridouille :

I want to second this question. Thanks in advance for some clarification.

**Comment by Bridouille** [comment]
All the code is right here in the repo for you to check out. It's not even in Java.
