### ISSUE TITLE
Editing Major & Minors ?

### ISSUE THREAD

**Issue by 1stmetro** [Bridouille/android-beacon-scanner#5]
I managed to get this running quite easy !

Now i'm wondering how to write the major and minor numbers and edit the tx power.

Also is there a way to see all the fields for the beacons i have as i'm unsure what fields they actually have and may need to exit these additional fields.

**Comment by lakshmanpasala** [comment]
You can't edit the major, minor and tx power from this app. You should use the manufacturer's app instead, e.g. if you are using estimote beacons then you can use their app to adjust the Tx Power

**Comment by 1stmetro** [comment]
I have beacons that I have i believe are ibeacons 0x004c I believe is the manufacture code.

So unsure where to get an app to set majors and minors any ideal?

**Comment by Bridouille** [comment]
Usually when you buy beacons, the manufacturer gives you a set of tools to edit what the beacons are emitting. Examples of manufacturers are [radiusnetwork](https://www.radiusnetworks.com/?PhoneScript=ppc&opti_ca=736962455&opti_ag=33967370370&opti_ad=174451723379&opti_key=kwd-55693888183&gclid=Cj0KCQjwktHLBRDsARIsAFBSb6xEB6eFzORxaWM54wtia0u-aCSzO8UTP5XC0vnPdQaD5KIQlKEhmEIaAiwpEALw_wcB) and [estimote](http://estimote.com/). In summary, try to see if the place where you bought the beacons is providing any app for doing this.

**Comment by 1stmetro** [comment]
Problem is I didn't buy the beacons but have over 100

**Comment by Bridouille** [comment]
You should try to contact the manufacturer of your beacons and see if they can provide you an app that can actually edit the infos that are emitted by those.
