### ISSUE TITLE
Distance Calculation

### ISSUE THREAD

**Issue by 1stmetro** [Bridouille/android-beacon-scanner#6]
The distance calculation appears to be way off, can you point me in the right direction where the calculation code is located ?

**Comment by lakshmanpasala** [comment]
The RSSI values vary a lot depending on the environment. For closer distances the computed values shouldn't be way off but as you go further away the computed values are known to be way off. 
I'd suggest you use Kalman Filter to normalize the RSSI values and then compute the distance.

**Comment by 1stmetro** [comment]
I have over a hundred ibeacons to index so I will be looking to sort the list on major and minor but thanks for your answer on rssi

**Comment by Bridouille** [comment]
Hi! The distance is calculated by the library alt-beacon: [Have a read here](http://altbeacon.github.io/android-beacon-library/distance-calculations.html)
([assigned here](https://github.com/Bridouille/android-beacon-scanner/blob/master/app/src/main/java/com/bridou_n/beaconscanner/features/beaconList/MainActivity.java#L200))

**Comment by lakshmanpasala** [comment]
Just a word of caution, do not depend on BLEs and the distance computed for indoor navigation if that is what your use case is.
