### ISSUE TITLE
Formate of the lastSeen field

### ISSUE THREAD

**Issue by PascalMinder** [Bridouille/android-beacon-scanner#8]
What type of format has the lastSeen file if I use the logging function

**Comment by Bridouille** [comment]
The `lastSeen` field is a timestamp representing the date when the beacon has been scanned for the last time!

**Comment by PascalMinder** [comment]
I know that, but what I didn't know was, that the time is a unix timestamp with the ms added to it.

**Comment by Bridouille** [comment]
Yep exactly.

Small note on this one, the timestamp is taken in the timezone from where the phone is setup.
