### ISSUE TITLE
"Copy to clipboard" generates not well formatted JSON

### ISSUE THREAD

**Issue by brunoandretto** [Bridouille/android-beacon-scanner#9]
Hello!

I just downloaded the app from Play Store (current version: 2.1.0) into my Motorola G4 running Android 7.0. 
While I was testing it, i noticed the "press and hold" to copy information from a card to my clipboard, such as this one:

![2435723516812825707](https://user-images.githubusercontent.com/19416293/34017402-c7b46934-e10c-11e7-84d4-0e81a6d33a0b.png)

And to my surprise it actually copied all of the cards information into a JSON, which is amazing. The issue is, though, that the JSON seens to be inappropriate:

> {
	"beaconAddress": "D3:7B:ED:3D:59:CF",
	"beaconType": "eddystone_uid",
	"distance": 1.0083072011759482,
	"hashcode": -430272489,
	"isBlocked": false,
	"lastMinuteSeen": 25221370,
	"lastSeen": 1513282215216,
	"manufacturer": 65194,
	"rssi": -82,
	"txPower": -81 "eddystoneUidData": {
		"namespaceId": "0xf5ee50f5b45e7d9b0cb6"
		"instanceId": 0x000091eb78ff,
	},
}

This one, for example, will break because of the commas. It also happened to iBeacons frame.

Thanks for the great app.

Best regards

**Comment by Bridouille** [comment]
Hi!

You're absolutely right, I was formatting the JSON by hand to omit certain fields that aren't relevant to the data (business logic in the app).

I need to make a fix to exclude them from the JSON and use the standard JSON encoding 👍

**Comment by Bridouille** [comment]
Should be fixed in : https://github.com/Bridouille/android-beacon-scanner/commit/52d30d9b5fab47b3742db61e477cc9be1112f7b9

Going to release it in `2.1.1`
